### ISSUE TITLE
Tasks Page

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#47]
Hey Rodolfo, may I get more details about these series of pages?

**Comment by rodolfomartinez** [comment]
@bartmika I think we should discuss this one face to face - this is reslly a visualization of the rules that get triggerred by the "life of s blue sheet". For example, if a job was created, a team member should contact the client within 48 business hours to make sure that an Associate has called them.  It should be a simple list of tasks that can be marked as done, and as much as possible should conform to current Ui so that we don't have to dev anything new.

**Comment by bartmika** [comment]
@rodolfomartinez We have all we need for me to begin implementing this!
